apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: tibco-customers
  description: An organization that manage customers
  tags:
    - customers
    - platform
spec:
  type: organization
  profile:
    displayName: TIBCO CRM
    email: info@tibco.com
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: customers
  description: Everything related to customers
  tags:
    - customers
    - platform
spec:
  owner: tibco-customers
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: customer-system
  description: 'A system to manage customers'
  tags:
    - customers
    - platform
spec:
  owner: tibco-customers
  domain: customers
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "CustomerAPI-Hicham"
  description: "A service that calls a backend customer service using Flogo - developped by Hicham"
  tags: 
    - customers
    - platform
  links:
    - title: Flogo Documentation
      url: https://docs.tibco.com/products/tibco-flogo-enterprise
    - title: VSCode Editor (File)
      url: vscode://file//Users/hicham/git/CustomerAPI-Hicham/src/customer-api.flogo
    - title: VSCode Editor (Folder)
      url: vscode://file//Users/hicham/git/CustomerAPI-Hicham
  tibcoPlatformApps:
    - appType: Flogo
      appName: CustomerAPI-Hicham
      dataPlaneName: dp-aks
      dpId: cq35s2ijcp26pefl1dmg
      capabilityInstanceId: cqgcsnijcp26pefl1g20
      appId: v4f54zzzzzzz7g67
  annotations:
    jenkins.io/job-full-name: CustomerAPI-HichamJob
    github.com/project-slug: atsfr-tibco-devhub/CustomerAPI-Hicham
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  system: customer-system
  lifecycle: development
  owner: tibco-customers
  dependsOn:
    - component:default/customer-backend
  providesApis: ['CustomerAPI-Hicham-api']
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: 'CustomerAPI-Hicham-api'
  description: 'An API that manages customers'
  tags:
    - customers
    - rest
    - platform
spec:
  type: openapi
  lifecycle: development
  system: CustomerAPI-Hicham-system
  owner: tibco-customers
  apiConsumedBy:
    []
  definition:
    $text: "./spec/customer.json"
